### ISSUE TITLE
Is this project still active? Unable to open dongle.

### ISSUE THREAD

**Issue by LividJava** [julr/obs-ant-hrm#2]
I'm encountering an error, Just getting a generic "Unable to open dongle device", I am using a supported dongle, its quite literally the same Cycplus dongle of that I'm positive.

I don't have any logs or anything to go off of.

**Comment by julr** [comment]
I am currently not actively developing this project but it should still work. "Unable to open dongle device" means that a compatible device was found but libUSB can't access it. Which drivers are you using? I just tested the lastest libusb-win32 (v1.2.7.3) installed via Zadig and that worked for me.

**Comment by LividJava** [comment]
I'm using the one from Zadig?? im uncertain as to whats going on

**Comment by LividJava** [comment]
Wait hang on, realized i was using WinUSB and not libusb lemme swap it and see

**Comment by LividJava** [comment]
Okay yeah, was using WinUSB and not libusb, didn't realize that you could change whichever one was installed
